[[pages]]
path = "app.py"
name = "Home"
icon = "🏠"

[[pages]]
path = "pages/page2.py"
name = "Page 2"
icon = ":books"

[[pages]]
name = "My second"
icon = "🎈️"
is_section = true

# Pages after an `is_section = true` will be indented
[[pages]]
name = "Another page"
icon = "💪"

# Unless you explicitly say in_section = false`
[[pages]]
name = "Not in a section"
in_section = false